# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZpmlemQd4Xza9wcdODb8UYAv3nWVocdY
"""

x = 5
print(f"變數x的值為:{x}")
print(f"變數x的記憶地址為:{id(x)}")